app.controller('autoComplete', autoComplete);

  function autoComplete ($timeout, $q, $log) {
    var self = this;

    self.simulateQuery = false;
    self.isDisabled    = false;

    self.repos         = loadAll();
    self.querySearch   = querySearch;
    self.selectedItemchange = selectedItemchange;
    self.searchTextChange   = searchTextChange;

    // *****************************
    // Internal methods
    // ******************************

    /**
     * Search for repos... use $timeout to simulate
     * remote dataservice call.
     */
    function querySearch (query) {
      var results = query ? self.repos.filter( createFilterFor(query) ) : self.repos,
          deferred;
      if (self.simulateQuery) {
        deferred = $q.defer();
        $timeout(function () { deferred.resolve( results ); }, Math.random() * 1000, false);
        return deferred.promise;
      } else {
        return results;
      }
    }

    function searchTextChange(text) {
      $log.info('Text changed to ' + text);
    }

    function selectedItemchange(item) {
      $log.info('Item changed to ' + JSON.stringify(item));
      // document.location.target='_blank';
      idLegis = JSON.stringify(item.id).replace(/['"]+/g, '');
      // window.location = "hola.html?id="+idLegis, "_blank";
      window.open("sites/profile.html?id="+idLegis,'_blank');



    }

    /**
     * Build `components` list of key/value pairs
     */
    function loadAll() {
      var repos = [
        {'chamber':'Dip.','id':'9218925','name':'Aarón González Rojas','party':'pri'},
        {'chamber':'Dip.','id':'9221503','name':'Abdies Pineda Morín','party':'pes'},
        {'chamber':'Dip.','id':'9219550','name':'Abel Murrieta Gutiérrez','party':'pri'},
        {'chamber':'Dip.','id':'9219113','name':'Adán Pérez Utrera','party':'mc'},
        {'chamber':'Dip.','id':'9219566','name':'Adolfo Mota Hernández','party':'pri'},
        {'chamber':'Dip.','id':'9218355','name':'Adriana del Pilar Ortiz Lanz','party':'pri'},
        {'chamber':'Dip.','id':'9219329','name':'Adriana Elizarraraz Sandoval','party':'pan'},
        {'chamber':'Dip.','id':'9219021','name':'Adriana Sarur Torre','party':'pvem'},
        {'chamber':'Dip.','id':'9218902','name':'Adriana Terrazas Porras','party':'pri'},
        {'chamber':'Dip.','id':'9219255','name':'Agustín Francisco de Asís Basave Benítez','party':'prd'},
        {'chamber':'Dip.','id':'9218422','name':'Alberto Martínez Urincho','party':'morena'},
        {'chamber':'Dip.','id':'9219063','name':'Alberto Silva Ramos','party':'pri'},
        {'chamber':'Dip.','id':'9219622','name':'Alejandra Gutiérrez Campos','party':'pan'},
        {'chamber':'Dip.','id':'9219586','name':'Alejandra Noemí Reynoso Sánchez','party':'pan'},
        {'chamber':'Dip.','id':'9219143','name':'Alejandro Armenta Mier','party':'morena'},
        {'chamber':'Dip.','id':'9219111','name':'Alejandro González Murillo','party':'pes'},
        {'chamber':'Dip.','id':'9218938','name':'Alejandro Juraidini Villaseñor','party':'pri'},
        {'chamber':'Dip.','id':'9218906','name':'Alex Le Baron González','party':'pri'},
        {'chamber':'Dip.','id':'9221521','name':'Alfredo Anaya Orozco','party':'pri'},
        {'chamber':'Dip.','id':'9219345','name':'Alfredo Basurto Román','party':'morena'},
        {'chamber':'Dip.','id':'9219001','name':'Alfredo Bejos Nicolás','party':'pri'},
        {'chamber':'Dip.','id':'9218464','name':'Alfredo Javier Rodríguez  Dávila','party':'pan'},
        {'chamber':'Dip.','id':'9218450','name':'Alfredo Miguel Herrera Deras','party':'pan'},
        {'chamber':'Dip.','id':'9219763','name':'Alicia Barrientos pantoja','party':'morena'},
        {'chamber':'Dip.','id':'9219123','name':'Alicia Guadalupe Gamboa Martínez','party':'pri'},
        {'chamber':'Dip.','id':'9218722','name':'Alma Carolina Viggiano Austria','party':'pri'},
        {'chamber':'Dip.','id':'9219752','name':'Alma Lilia Luna Munguía','party':'pri'},
        {'chamber':'Dip.','id':'9219494','name':'Alma Lucía Arzaluz Alonso','party':'pvem'},
        {'chamber':'Dip.','id':'9219014','name':'Ana Georgina Zapata Lucero','party':'pri'},
        {'chamber':'Dip.','id':'9219129','name':'Ana Guadalupe Perea Santos','party':'pes'},
        {'chamber':'Dip.','id':'9219241','name':'Ana Leticia Carrera Hernández','party':'morena'},
        {'chamber':'Dip.','id':'9218909','name':'Ana María Boone Godoy','party':'pri'},
        {'chamber':'Dip.','id':'9219446','name':'Andrés Aguirre Romero','party':'pri'},
        {'chamber':'Dip.','id':'9218886','name':'Andrés Fernández del Valle Laisequilla','party':'pvem'},
        {'chamber':'Dip.','id':'9218616','name':'Angélica Moya Marín','party':'pan'},
        {'chamber':'Dip.','id':'9219391','name':'Angélica Reyes ívila','party':'panal'},
        {'chamber':'Dip.','id':'9219672','name':'Angie Dennisse Hauffen Torres','party':'mc'},
        {'chamber':'Dip.','id':'9218736','name':'Antonio Amaro Cancino','party':'pri'},
        {'chamber':'Dip.','id':'9219031','name':'Antonio Enrique Tarín García','party':'pri'},
        {'chamber':'Dip.','id':'9218979','name':'Antonio Tarek Abdala Saad','party':'pri'},
        {'chamber':'Dip.','id':'9221526','name':'Araceli Damián González','party':'morena'},
        {'chamber':'Dip.','id':'9219694','name':'Araceli Guerrero Esquivel','party':'pri'},
        {'chamber':'Dip.','id':'9219610','name':'Araceli Madrigal Sánchez','party':'prd'},
        {'chamber':'Dip.','id':'9219747','name':'Araceli Saucedo Reyes','party':'prd'},
        {'chamber':'Dip.','id':'9219261','name':'Ariadna Montiel Reyes','party':'morena'},
        {'chamber':'Dip.','id':'9219648','name':'Ariel Enrique Corona Rodríguez','party':'pan'},
        {'chamber':'Dip.','id':'9219564','name':'Arlet Mólgora Glover','party':'pri'},
        {'chamber':'Dip.','id':'9218484','name':'Arlette Ivette Muñoz Cervantes','party':'pan'},
        {'chamber':'Dip.','id':'9218470','name':'Armando Alejandro Rivera Castillejos','party':'pan'},
        {'chamber':'Dip.','id':'9219023','name':'Armando Luna Canales','party':'pri'},
        {'chamber':'Dip.','id':'9219576','name':'Armando Soto Espino','party':'prd'},
        {'chamber':'Dip.','id':'9219760','name':'Arturo Álvarez Angli','party':'pvem'},
        {'chamber':'Dip.','id':'9219237','name':'Arturo Santana Alfaro','party':'prd'},
        {'chamber':'Dip.','id':'9218323','name':'Baltazar Manuel Hinojosa Ochoa','party':'pri'},
        {'chamber':'Dip.','id':'9218478','name':'Baltazar Martínez Montemayor','party':'pan'},
        {'chamber':'Dip.','id':'9219714','name':'Beatriz Vélez Núñez','party':'pri'},
        {'chamber':'Dip.','id':'9219562','name':'Benjamín Medrano Quezada','party':'pri'},
        {'chamber':'Dip.','id':'9218907','name':'Bernardino Antelo Esper','party':'pri'},
        {'chamber':'Dip.','id':'9219502','name':'Blanca Margarita Cuata Domínguez','party':'morena'},
        {'chamber':'Dip.','id':'9219518','name':'Blandina Ramos Ramírez','party':'morena'},
        {'chamber':'Dip.','id':'9221532','name':'Braulio Mario Guerra Urbiola','party':'pri'},
        {'chamber':'Dip.','id':'9218299','name':'Brenda Borunda Espinoza','party':'pri'},
        {'chamber':'Dip.','id':'9218522','name':'Brenda Velázquez Valdez','party':'pan'},
        {'chamber':'Dip.','id':'9219263','name':'Candelario Pérez Alvarado','party':'prd'},
        {'chamber':'Dip.','id':'9219478','name':'Cándido Ochoa Rojas','party':'pvem'},
        {'chamber':'Dip.','id':'9218646','name':'Carlos Alberto De la Fuente Flores','party':'pan'},
        {'chamber':'Dip.','id':'9219404','name':'Carlos Alberto Palomeque Archila','party':'pan'},
        {'chamber':'Dip.','id':'9219458','name':'Carlos Barragán Amador','party':'pri'},
        {'chamber':'Dip.','id':'9218814','name':'Carlos Bello Otero','party':'pan'},
        {'chamber':'Dip.','id':'9218357','name':'Carlos Federico Quinto Guillén','party':'pri'},
        {'chamber':'Dip.','id':'9219029','name':'Carlos Gerardo Hermosillo Arteaga','party':'pri'},
        {'chamber':'Dip.','id':'9219620','name':'Carlos Gutiérrez García','party':'panal'},
        {'chamber':'Dip.','id':'9219167','name':'Carlos Hernández Mirón','party':'morena'},
        {'chamber':'Dip.','id':'9218700','name':'Carlos Iriarte Mercado','party':'pri'},
        {'chamber':'Dip.','id':'9221501','name':'Carlos Lomelí Bolaños','party':'morena'},
        {'chamber':'Dip.','id':'9219055','name':'Carlos Sarabia Camacho','party':'pri'},
        {'chamber':'Dip.','id':'9218391','name':'Carmen Salinas Lozano','party':'pri'},
        {'chamber':'Dip.','id':'9219383','name':'Carmen Victoria Campa Almaral','party':'panal'},
        {'chamber':'Dip.','id':'9219037','name':'Carolina Monroy Del Mazo','party':'pri'},
        {'chamber':'Dip.','id':'9219295','name':'Cecilia Guadalupe Soto González','party':'prd'},
        {'chamber':'Dip.','id':'9219027','name':'César Alejandro Domínguez Domínguez','party':'pri'},
        {'chamber':'Dip.','id':'9218528','name':'César Augusto Rendón García','party':'pan'},
        {'chamber':'Dip.','id':'9218486','name':'César Flores Sosa','party':'pan'},
        {'chamber':'Dip.','id':'9218397','name':'César Octavio Camacho Quiroz','party':'pri'},
        {'chamber':'Dip.','id':'9219582','name':'Cesáreo Jorge Márquez Alvarado','party':'pvem'},
        {'chamber':'Dip.','id':'9218951','name':'Charbel Jorge Estefan Chidiac','party':'pri'},
        {'chamber':'Dip.','id':'9218877','name':'Christian Joaquín Sánchez Sánchez','party':'pri'},
        {'chamber':'Dip.','id':'9219065','name':'Cirilo Vázquez Parissi','party':'pri'},
        {'chamber':'Dip.','id':'9219676','name':'Claudia Edith Anaya Mota','party':'pri'},
        {'chamber':'Dip.','id':'9218818','name':'Claudia Sánchez Juárez','party':'pan'},
        {'chamber':'Dip.','id':'9219674','name':'Claudia Sofía Corichi García','party':'mc'},
        {'chamber':'Dip.','id':'9218385','name':'Claudia Villanueva Huerta','party':'pvem'},
        {'chamber':'Dip.','id':'9219434','name':'Concepción Villa González','party':'morena'},
        {'chamber':'Dip.','id':'9219287','name':'Cristina Ismene Gaytán Hernández','party':'prd'},
        {'chamber':'Dip.','id':'9219033','name':'Cristina Sánchez Coronel','party':'pri'},
        {'chamber':'Dip.','id':'9219636','name':'Cuitláhuac García Jiménez','party':'morena'},
        {'chamber':'Dip.','id':'9219215','name':'Cynthia Gissel García Soberanes','party':'pes'},
        {'chamber':'Dip.','id':'9219235','name':'Daniel Ordóñez Hernández','party':'prd'},
        {'chamber':'Dip.','id':'9218452','name':'Daniela De los Santos Torres','party':'pvem'},
        {'chamber':'Dip.','id':'9219499','name':'Daniela García Treviño','party':'pvem'},
        {'chamber':'Dip.','id':'9218383','name':'David Aguilar Robles','party':'pri'},
        {'chamber':'Dip.','id':'9218277','name':'David Epifanio López Gutiérrez','party':'pri'},
        {'chamber':'Dip.','id':'9218269','name':'David Gerson García Calderón','party':'prd'},
        {'chamber':'Dip.','id':'9219542','name':'David Jiménez Rumbo','party':'prd'},
        {'chamber':'Dip.','id':'9219596','name':'David Mercado Ruiz','party':'pri'},
        {'chamber':'Dip.','id':'9219035','name':'David Sánchez Isidoro','party':'pri'},
        {'chamber':'Dip.','id':'9218424','name':'Delfina Gómez Álvarez','party':'morena'},
        {'chamber':'Dip.','id':'9218327','name':'Delia Guerrero Coronado','party':'pri'},
        {'chamber':'Dip.','id':'9219239','name':'Diego Valente Valera Fuentes','party':'prd'},
        {'chamber':'Dip.','id':'9219568','name':'Dora Elena Real Salinas','party':'pri'},
        {'chamber':'Dip.','id':'9218401','name':'Dulce María Montes Salas','party':'pri'},
        {'chamber':'Dip.','id':'9218915','name':'Edgar Castillo Martínez','party':'pri'},
        {'chamber':'Dip.','id':'9218728','name':'Edgar Romo García','party':'pri'},
        {'chamber':'Dip.','id':'9218881','name':'Edgardo Melhem Salinas','party':'pri'},
        {'chamber':'Dip.','id':'9218967','name':'Edith Anabel Alvarado Varela','party':'pri'},
        {'chamber':'Dip.','id':'9219049','name':'Edith Villa Trujillo','party':'pri'},
        {'chamber':'Dip.','id':'9218921','name':'Edith Yolanda López Velasco','party':'pri'},
        {'chamber':'Dip.','id':'9218620','name':'Edmundo Javier Bolaños Aguilar','party':'pan'},
        {'chamber':'Dip.','id':'9218957','name':'Edna González Evia','party':'pvem'},
        {'chamber':'Dip.','id':'9219584','name':'Edna Ileana Dávalos Elizondo','party':'pri'},
        {'chamber':'Dip.','id':'9218989','name':'Efraín Arellano Núñez','party':'pri'},
        {'chamber':'Dip.','id':'9219332','name':'Elías Octavio íñiguez Mejía','party':'pan'},
        {'chamber':'Dip.','id':'9219504','name':'Elías Ojeda Aquino','party':'morena'},
        {'chamber':'Dip.','id':'9219606','name':'Elio Bocanegra Ruiz','party':'prd'},
        {'chamber':'Dip.','id':'9219680','name':'Eloisa Chavarrías Barajas','party':'pan'},
        {'chamber':'Dip.','id':'9218480','name':'Elva Lidia Valles Olvera','party':'pan'},
        {'chamber':'Dip.','id':'9218696','name':'Elvia Graciela Palomares Ramírez','party':'pri'},
        {'chamber':'Dip.','id':'9221502','name':'Emilio Enrique Salazar Farías','party':'pvem'},
        {'chamber':'Dip.','id':'9218656','name':'Emma Margarita Alemán Olvera','party':'pan'},
        {'chamber':'Dip.','id':'9218562','name':'Enrique Cambranis Torres','party':'pan'},
        {'chamber':'Dip.','id':'9219598','name':'Enrique Rojas Orozco','party':'pri'},
        {'chamber':'Dip.','id':'9219474','name':'Enrique Zamora Morlet','party':'pvem'},
        {'chamber':'Dip.','id':'9218987','name':'Erick Alejandro Lagos Hernández','party':'pri'},
        {'chamber':'Dip.','id':'9219702','name':'Erik Juárez Blanquet','party':'prd'},
        {'chamber':'Dip.','id':'9218698','name':'Erika Araceli Rodríguez Hernández','party':'pri'},
        {'chamber':'Dip.','id':'9218273','name':'Erika Irazema Briones Pérez','party':'prd'},
        {'chamber':'Dip.','id':'9219590','name':'Erika Lorena Arroyo Bello','party':'pri'},
        {'chamber':'Dip.','id':'9219690','name':'Ernestina Godoy Ramos','party':'morena'},
        {'chamber':'Dip.','id':'9218961','name':'Esdras Romero Vega','party':'pri'},
        {'chamber':'Dip.','id':'9218291','name':'Esthela de Jesús Ponce Beltrán','party':'pri'},
        {'chamber':'Dip.','id':'9218607','name':'Eukid Castañón Herrera','party':'pan'},
        {'chamber':'Dip.','id':'9218267','name':'Eva Florinda Cruz Molina','party':'prd'},
        {'chamber':'Dip.','id':'9218958','name':'Evelio Plata Inzunza','party':'pri'},
        {'chamber':'Dip.','id':'9219227','name':'Evelyn Parra Álvarez','party':'prd'},
        {'chamber':'Dip.','id':'9219612','name':'Evelyng Soraya Flores Carranza','party':'pvem'},
        {'chamber':'Dip.','id':'9218490','name':'Exaltación González Ceceña','party':'pan'},
        {'chamber':'Dip.','id':'9219452','name':'Fabiola Guerrero Aguilar','party':'pri'},
        {'chamber':'Dip.','id':'9218969','name':'Fabiola Rosas Cuautle','party':'pri'},
        {'chamber':'Dip.','id':'9218594','name':'Federico Döring Casar','party':'pan'},
        {'chamber':'Dip.','id':'9219044','name':'Federico Eugenio Vargas Rodríguez','party':'pri'},
        {'chamber':'Dip.','id':'9219196','name':'Felipe Cervera Hernández','party':'pri'},
        {'chamber':'Dip.','id':'9219271','name':'Felipe Reyes Álvarez','party':'prd'},
        {'chamber':'Dip.','id':'9218389','name':'Fernando Navarrete Pérez','party':'pri'},
        {'chamber':'Dip.','id':'9218730','name':'Fernando Quetzalcóatl Moctezuma Pereda','party':'pri'},
        {'chamber':'Dip.','id':'9218720','name':'Fernando Uriarte Zazueta','party':'pri'},
        {'chamber':'Dip.','id':'9218931','name':'Fidel Almanza Monroy','party':'pri'},
        {'chamber':'Dip.','id':'9219341','name':'Fidel Calderón Torreblanca','party':'morena'},
        {'chamber':'Dip.','id':'9218943','name':'Fidel Cristóbal Serrato','party':'pri'},
        {'chamber':'Dip.','id':'9219022','name':'Fidel Kuri Grajales','party':'pri'},
        {'chamber':'Dip.','id':'9219025','name':'Flor Estela Rentería Medina','party':'pri'},
        {'chamber':'Dip.','id':'9219085','name':'Flor íngel Jiménez Jiménez','party':'pri'},
        {'chamber':'Dip.','id':'9219716','name':'Francisco Alberto Torres Rivas','party':'pvem'},
        {'chamber':'Dip.','id':'9219468','name':'Francisco Escobedo Villegas','party':'pri'},
        {'chamber':'Dip.','id':'9219390','name':'Francisco Javier Pinto Torres','party':'panal'},
        {'chamber':'Dip.','id':'9218307','name':'Francisco Javier Santillán Oceguera','party':'pri'},
        {'chamber':'Dip.','id':'9221543','name':'Francisco José Gutiérrez de Velasco Urtaza','party':'pan'},
        {'chamber':'Dip.','id':'9219460','name':'Francisco Lauro Rojas San Román','party':'pri'},
        {'chamber':'Dip.','id':'9218265','name':'Francisco Martínez Neri','party':'prd'},
        {'chamber':'Dip.','id':'9218602','name':'Francisco Ricardo Sheffield Padilla','party':'pan'},
        {'chamber':'Dip.','id':'9219578','name':'Francisco Saracho Navarro','party':'pri'},
        {'chamber':'Dip.','id':'9221530','name':'Francisco Xavier Nava Palacios','party':'prd'},
        {'chamber':'Dip.','id':'9219141','name':'Gabriel Casillas Zanatta','party':'pri'},
        {'chamber':'Dip.','id':'9219534','name':'Gabriela Ramírez Ramos','party':'pan'},
        {'chamber':'Dip.','id':'9218664','name':'Genoveva Huerta Villegas','party':'pan'},
        {'chamber':'Dip.','id':'9218363','name':'Georgina Trujillo Zentella','party':'pri'},
        {'chamber':'Dip.','id':'9219401','name':'Gerardo Federico Salas Díaz','party':'pan'},
        {'chamber':'Dip.','id':'9218670','name':'Gerardo Gabriel Cuanalo Santos','party':'pan'},
        {'chamber':'Dip.','id':'9219642','name':'Germán Ernesto Ralis Cumplido','party':'mc'},
        {'chamber':'Dip.','id':'9218959','name':'Germán Escobar Manjarrez','party':'pri'},
        {'chamber':'Dip.','id':'9218941','name':'Gianni Raúl Ramírez Ocampo','party':'pri'},
        {'chamber':'Dip.','id':'9218458','name':'Gina Andrea Cruz Blackledge','party':'pan'},
        {'chamber':'Dip.','id':'9219005','name':'Gloria Himelda Félix Niebla','party':'pri'},
        {'chamber':'Dip.','id':'9219079','name':'Gonzalo Guízar Valladares','party':'pes'},
        {'chamber':'Dip.','id':'9218790','name':'Gretel Culin Jaime','party':'pan'},
        {'chamber':'Dip.','id':'9219245','name':'Guadalupe Acosta Naranjo','party':'prd'},
        {'chamber':'Dip.','id':'9218662','name':'Guadalupe González Suástegui','party':'pan'},
        {'chamber':'Dip.','id':'9219614','name':'Guadalupe Hernández Correa','party':'morena'},
        {'chamber':'Dip.','id':'9219558','name':'Guillermo Rafael Santiago Rodríguez','party':'morena'},
        {'chamber':'Dip.','id':'9219410','name':'Gustavo Adolfo Cárdenas Gutiérrez','party':'mc'},
        {'chamber':'Dip.','id':'9218596','name':'Héctor Barrera Marmolejo','party':'pan'},
        {'chamber':'Dip.','id':'9218708','name':'Héctor Javier Álvarez Ortiz','party':'pri'},
        {'chamber':'Dip.','id':'9219660','name':'Héctor Javier García Chávez','party':'morena'},
        {'chamber':'Dip.','id':'9219765','name':'Héctor Peralta Grappin','party':'prd'},
        {'chamber':'Dip.','id':'9219696','name':'Héctor Ulises Cristopulos Ríos','party':'pri'},
        {'chamber':'Dip.','id':'9219552','name':'Heidi Salazar Espinosa','party':'pri'},
        {'chamber':'Dip.','id':'9218434','name':'Herminio Corral Estrada','party':'pan'},
        {'chamber':'Dip.','id':'9219574','name':'Hernán de Jesús Orantes López','party':'pri'},
        {'chamber':'Dip.','id':'9218395','name':'Hersilia Onfalia Adamina Córdova Morán','party':'pri'},
        {'chamber':'Dip.','id':'9219247','name':'Hortensia Aragón Castillo','party':'prd'},
        {'chamber':'Dip.','id':'9221505','name':'Hugo Alejo Domínguez','party':'pan'},
        {'chamber':'Dip.','id':'9218913','name':'Hugo Daniel Gaeta Esparza','party':'pri'},
        {'chamber':'Dip.','id':'9218333','name':'ílvaro Ibarra Hinojosa','party':'pri'},
        {'chamber':'Dip.','id':'9218887','name':'ílvaro Rafael Rubio','party':'pri'},
        {'chamber':'Dip.','id':'9219432','name':'íngel Antonio Hernández de la Piedra','party':'morena'},
        {'chamber':'Dip.','id':'9219670','name':'íngel García Yáñez','party':'panal'},
        {'chamber':'Dip.','id':'9219710','name':'íngel II Alanís Pedraza','party':'prd'},
        {'chamber':'Dip.','id':'9221507','name':'Ingrid Krasopani Schemelensky Castro','party':'pan'},
        {'chamber':'Dip.','id':'9219602','name':'Irma Rebeca López López','party':'prd'},
        {'chamber':'Dip.','id':'9219283','name':'Isaura Ivanova Pool Pech','party':'prd'},
        {'chamber':'Dip.','id':'9219139','name':'Iveth Bernal Casique','party':'pri'},
        {'chamber':'Dip.','id':'9218672','name':'J. Apolinar Casillas Gutiérrez','party':'pan'},
        {'chamber':'Dip.','id':'9219017','name':'J. Jesús Zúñiga Mendoza','party':'pri'},
        {'chamber':'Dip.','id':'9218516','name':'Jacqueline Nava Mouett','party':'pan'},
        {'chamber':'Dip.','id':'9218544','name':'Janette Ovando Reazola','party':'pan'},
        {'chamber':'Dip.','id':'9218945','name':'Jasmine María Bugarín Rodríguez','party':'pri'},
        {'chamber':'Dip.','id':'9219526','name':'Javier Antonio Neblina Vega','party':'pan'},
        {'chamber':'Dip.','id':'9218992','name':'Javier Octavio Herrera Borunda','party':'pvem'},
        {'chamber':'Dip.','id':'9219169','name':'Jerónimo Alejandro Ojeda Anguiano','party':'morena'},
        {'chamber':'Dip.','id':'9219397','name':'Jesús Antonio López Rodríguez','party':'pan'},
        {'chamber':'Dip.','id':'9219440','name':'Jesús Emiliano Álvarez López','party':'morena'},
        {'chamber':'Dip.','id':'9218293','name':'Jesús Enrique Jackson Ramírez','party':'pri'},
        {'chamber':'Dip.','id':'9218899','name':'Jesús Gerardo Izquierdo Rojas','party':'pvem'},
        {'chamber':'Dip.','id':'9219385','name':'Jesús Rafael Méndez Salas','party':'panal'},
        {'chamber':'Dip.','id':'9219730','name':'Jesús Ricardo Canavati Tafich','party':'pvem'},
        {'chamber':'Dip.','id':'9219339','name':'Jesús Salvador Valencia Guzmán','party':'morena'},
        {'chamber':'Dip.','id':'9219522','name':'Jesús Serrano Lora','party':'morena'},
        {'chamber':'Dip.','id':'9219728','name':'Jesús Sesma Suárez','party':'pvem'},
        {'chamber':'Dip.','id':'9218574','name':'Jisela Paes Martínez','party':'pan'},
        {'chamber':'Dip.','id':'9218546','name':'Joaquín Jesús Díaz Mena','party':'pan'},
        {'chamber':'Dip.','id':'9219426','name':'Jonadab Martínez García','party':'mc'},
        {'chamber':'Dip.','id':'9218985','name':'Jorge Alejandro Carvallo Delfín','party':'pri'},
        {'chamber':'Dip.','id':'9219721','name':'Jorge Álvarez López','party':'pvem'},
        {'chamber':'Dip.','id':'9218953','name':'Jorge Álvarez Maynez','party':'mc'},
        {'chamber':'Dip.','id':'9218337','name':'Jorge Carlos Ramírez Marín','party':'pri'},
        {'chamber':'Dip.','id':'9218309','name':'Jorge Enrique Dávila Flores','party':'pri'},
        {'chamber':'Dip.','id':'9218488','name':'Jorge López Martín','party':'pan'},
        {'chamber':'Dip.','id':'9218496','name':'Jorge Ramos Hernández','party':'pan'},
        {'chamber':'Dip.','id':'9219604','name':'Jorge Tello López','party':'prd'},
        {'chamber':'Dip.','id':'9218592','name':'Jorge Triana Tena','party':'pan'},
        {'chamber':'Dip.','id':'9218937','name':'Jorgina Gaxiola Lezama','party':'pvem'},
        {'chamber':'Dip.','id':'9218650','name':'José Adrián González Navarro','party':'pan'},
        {'chamber':'Dip.','id':'9219043','name':'José Alberto Couttolenc Buentello','party':'pvem'},
        {'chamber':'Dip.','id':'9219776','name':'José Alfredo Ferreiro Velazco','party':'pes'},
        {'chamber':'Dip.','id':'9219454','name':'José Alfredo Torres Huitrón','party':'pri'},
        {'chamber':'Dip.','id':'9221541','name':'José Antonio Arévalo González','party':'pvem'},
        {'chamber':'Dip.','id':'9218259','name':'José Antonio Estefan Garfias','party':'prd'},
        {'chamber':'Dip.','id':'9218802','name':'José Antonio Salas Valencia','party':'pan'},
        {'chamber':'Dip.','id':'9219327','name':'José Clemente Castañeda Hoeflich','party':'mc'},
        {'chamber':'Dip.','id':'9219656','name':'José de Jesús Galindo Rosas','party':'pvem'},
        {'chamber':'Dip.','id':'9219285','name':'José de Jesús Zambrano Grijalva','party':'prd'},
        {'chamber':'Dip.','id':'9219652','name':'José del Pilar Córdova Hernández','party':'pri'},
        {'chamber':'Dip.','id':'9219638','name':'José Erandi Bermúdez Méndez','party':'pan'},
        {'chamber':'Dip.','id':'9221537','name':'José Everardo López Córdova','party':'pan'},
        {'chamber':'Dip.','id':'9219708','name':'José Guadalupe Hernández Alcalá','party':'prd'},
        {'chamber':'Dip.','id':'9218460','name':'José Hernán Cortés Berúmen','party':'pan'},
        {'chamber':'Dip.','id':'9219357','name':'José Hugo Cabrera Ruiz','party':'pri'},
        {'chamber':'Dip.','id':'9218935','name':'José Ignacio Pichardo Lechuga','party':'pri'},
        {'chamber':'Dip.','id':'9219313','name':'José Lorenzo Rivera Sosa','party':'pri'},
        {'chamber':'Dip.','id':'9219173','name':'José Luis Cardoso Estévez','party':'pri'},
        {'chamber':'Dip.','id':'9219019','name':'José Luis Orozco Sánchez Aldana','party':'pri'},
        {'chamber':'Dip.','id':'9218885','name':'José Luis Sáenz Soto','party':'pri'},
        {'chamber':'Dip.','id':'9219180','name':'José Luis Toledo Medina','party':'pri'},
        {'chamber':'Dip.','id':'9218498','name':'José Máximo García López','party':'pan'},
        {'chamber':'Dip.','id':'9219772','name':'José Refugio Sandoval Rodríguez','party':'pvem'},
        {'chamber':'Dip.','id':'9219554','name':'José Santiago López','party':'prd'},
        {'chamber':'Dip.','id':'9218438','name':'José Teodoro Barraza López','party':'pan'},
        {'chamber':'Dip.','id':'9218588','name':'Juan Alberto Blanco Zaldívar','party':'pan'},
        {'chamber':'Dip.','id':'9221520','name':'Juan Antonio Ixtláhuac Orihuela','party':'pri'},
        {'chamber':'Dip.','id':'9218903','name':'Juan Antonio Meléndez Ortega','party':'pri'},
        {'chamber':'Dip.','id':'9221531','name':'Juan Carlos Ruíz García','party':'pan'},
        {'chamber':'Dip.','id':'9218648','name':'Juan Corral Mier','party':'pan'},
        {'chamber':'Dip.','id':'9219293','name':'Juan Fernando Rubio Quiroz','party':'prd'},
        {'chamber':'Dip.','id':'9218947','name':'Juan Manuel Cavazos Balderas','party':'pri'},
        {'chamber':'Dip.','id':'9219600','name':'Juan Manuel Celis Aguirre','party':'pvem'},
        {'chamber':'Dip.','id':'9219334','name':'Juan Pablo Piña Kurczyn','party':'pan'},
        {'chamber':'Dip.','id':'9219436','name':'Juan Romero Tenorio','party':'morena'},
        {'chamber':'Dip.','id':'9218949','name':'Juana Aurora Cavazos Cavazos','party':'pri'},
        {'chamber':'Dip.','id':'9218714','name':'Julián Nazar Morales','party':'pri'},
        {'chamber':'Dip.','id':'9219706','name':'Julieta Fernández Márquez','party':'pri'},
        {'chamber':'Dip.','id':'9219281','name':'Julio Saldaña Morán','party':'prd'},
        {'chamber':'Dip.','id':'9219091','name':'Justo Federico Escobedo Miramontes','party':'pes'},
        {'chamber':'Dip.','id':'9219363','name':'Karen Hurtado Arana','party':'prd'},
        {'chamber':'Dip.','id':'9219265','name':'Karen Orney Ramírez Peralta','party':'prd'},
        {'chamber':'Dip.','id':'9221528','name':'Karina Padilla ívila','party':'pan'},
        {'chamber':'Dip.','id':'9219767','name':'Karina Sánchez Ruiz','party':'panal'},
        {'chamber':'Dip.','id':'9218526','name':'Karla Karina Osuna Carranco','party':'pan'},
        {'chamber':'Dip.','id':'9218548','name':'Kathia María Bolio Pinelo','party':'pan'},
        {'chamber':'Dip.','id':'9219508','name':'Laura Beatriz Esquivel Valdés','party':'morena'},
        {'chamber':'Dip.','id':'9218889','name':'Laura Mitzi Barrientos Cano','party':'pri'},
        {'chamber':'Dip.','id':'9219137','name':'Laura Nereida Plascencia Pacheco','party':'pri'},
        {'chamber':'Dip.','id':'9221539','name':'Laura Valeria Guzmán Vázquez','party':'pri'},
        {'chamber':'Dip.','id':'9219616','name':'Leonardo Amador Rodríguez','party':'prd'},
        {'chamber':'Dip.','id':'9219725','name':'Leonardo Rafael Guirao Aguilar','party':'pvem'},
        {'chamber':'Dip.','id':'9218520','name':'Leonel Gerardo Cordero Lerma','party':'pan'},
        {'chamber':'Dip.','id':'9219476','name':'Leticia Amparano Gámez','party':'pan'},
        {'chamber':'Dip.','id':'9219204','name':'Leydi Fabiola Leyva García','party':'pri'},
        {'chamber':'Dip.','id':'9219732','name':'Lía Limón García','party':'pvem'},
        {'chamber':'Dip.','id':'9219071','name':'Liborio Vidal Aguilar','party':'pri'},
        {'chamber':'Dip.','id':'9219396','name':'Lilia Arminda García Escobar','party':'pan'},
        {'chamber':'Dip.','id':'9219321','name':'Liliana Ivette Madrigal Méndez','party':'pri'},
        {'chamber':'Dip.','id':'9218983','name':'Lillian Zepahua García','party':'pri'},
        {'chamber':'Dip.','id':'9219351','name':'Lluvia Flores Sonduk','party':'prd'},
        {'chamber':'Dip.','id':'9221519','name':'Lorena Corona Valdés','party':'pvem'},
        {'chamber':'Dip.','id':'9218474','name':'Lorena del Carmen Alfaro García','party':'pan'},
        {'chamber':'Dip.','id':'9219359','name':'Lucely del Perpetuo Socorro Alpizar Carrillo','party':'pri'},
        {'chamber':'Dip.','id':'9219662','name':'Lucía Virginia Meza Guzmán','party':'morena'},
        {'chamber':'Dip.','id':'9218430','name':'Luis Agustín Rodríguez Torres','party':'pan'},
        {'chamber':'Dip.','id':'9219011','name':'Luis Alejandro Guevara Cobos','party':'pri'},
        {'chamber':'Dip.','id':'9219405','name':'Luis Alfredo Valles Mendoza','party':'panal'},
        {'chamber':'Dip.','id':'9218568','name':'Luis de León Martínez Sánchez','party':'pan'},
        {'chamber':'Dip.','id':'9219418','name':'Luis Ernesto Munguía González','party':'mc'},
        {'chamber':'Dip.','id':'9218738','name':'Luis Felipe Vázquez Guerrero','party':'pri'},
        {'chamber':'Dip.','id':'9219472','name':'Luis Fernando Antero Valle','party':'pan'},
        {'chamber':'Dip.','id':'9218426','name':'Luis Fernando Mesta Soulé','party':'pan'},
        {'chamber':'Dip.','id':'9218610','name':'Luis Gilberto Marrón Agustín','party':'pan'},
        {'chamber':'Dip.','id':'9219724','name':'Luis Ignacio Avendaño Bermúdez','party':'pvem'},
        {'chamber':'Dip.','id':'9219292','name':'Luis Maldonado Venegas','party':'prd'},
        {'chamber':'Dip.','id':'9219774','name':'Luis Manuel Hernández León','party':'panal'},
        {'chamber':'Dip.','id':'9218576','name':'Luz Argelia paniagua Figueroa','party':'pan'},
        {'chamber':'Dip.','id':'9219416','name':'Macedonio Salomón Tamez Guajardo','party':'mc'},
        {'chamber':'Dip.','id':'9218418','name':'Magdalena Moreno Vega','party':'morena'},
        {'chamber':'Dip.','id':'9219561','name':'Manuel de Jesús Espino Barrientos','party':'ind.'},
        {'chamber':'Dip.','id':'9219323','name':'Manuel Jesús Clouthier Carrillo','party':'ind.'},
        {'chamber':'Dip.','id':'9218386','name':'Manuel Vallejo Barragán','party':'pri'},
        {'chamber':'Dip.','id':'9219644','name':'Marbella Toledo Ibarra','party':'mc'},
        {'chamber':'Dip.','id':'9218977','name':'Marco Antonio Aguilar Yunes','party':'pri'},
        {'chamber':'Dip.','id':'9218933','name':'Marco Antonio Barranco Sánchez','party':'pri'},
        {'chamber':'Dip.','id':'9218502','name':'Marco Antonio Gama Basarte','party':'pan'},
        {'chamber':'Dip.','id':'9218303','name':'Marco Antonio García Ayala','party':'pri'},
        {'chamber':'Dip.','id':'9218871','name':'Marco Polo Aguirre Chávez','party':'pri'},
        {'chamber':'Dip.','id':'9218702','name':'María Angélica Mondragón Orozco','party':'pri'},
        {'chamber':'Dip.','id':'9219490','name':'María Antonia Cárdenas Mariscal','party':'morena'},
        {'chamber':'Dip.','id':'9218311','name':'María Bárbara Botello Santibáñez','party':'pri'},
        {'chamber':'Dip.','id':'9219424','name':'María Candelaria Ochoa ívalos','party':'mc'},
        {'chamber':'Dip.','id':'9219442','name':'María Chávez García','party':'morena'},
        {'chamber':'Dip.','id':'9219498','name':'María Concepción Valdés Ramírez','party':'prd'},
        {'chamber':'Dip.','id':'9218272','name':'María Cristina Teresa García Bravo','party':'prd'},
        {'chamber':'Dip.','id':'9219570','name':'María de la Paz Quiñones Cornejo','party':'pri'},
        {'chamber':'Dip.','id':'9218754','name':'María de los íngeles Rodríguez Aguirre','party':'pan'},
        {'chamber':'Dip.','id':'9219057','name':'María del Carmen Pinete Vargas','party':'pri'},
        {'chamber':'Dip.','id':'9219107','name':'María del Rocío Rebollo Mendoza','party':'pri'},
        {'chamber':'Dip.','id':'9219325','name':'María del Rocío Zazueta Osuna','party':'ind.'},
        {'chamber':'Dip.','id':'9218504','name':'María del Rosario Rodríguez Rubio','party':'pan'},
        {'chamber':'Dip.','id':'9219414','name':'María Elena Orantes López','party':'mc'},
        {'chamber':'Dip.','id':'9219488','name':'María Elida Castelán Mondragón','party':'prd'},
        {'chamber':'Dip.','id':'9218428','name':'María Eloísa Talavera Hernández','party':'pan'},
        {'chamber':'Dip.','id':'9218387','name':'María Esther de Jesús Scherman Leaño','party':'pri'},
        {'chamber':'Dip.','id':'9219122','name':'María Esther Guadalupe Camargo Félix','party':'pri'},
        {'chamber':'Dip.','id':'9219387','name':'María Eugenia Ocampo Bedolla','party':'panal'},
        {'chamber':'Dip.','id':'9218668','name':'María García Pérez','party':'pan'},
        {'chamber':'Dip.','id':'9218732','name':'María Gloria Hernández Madrid','party':'pri'},
        {'chamber':'Dip.','id':'9218706','name':'María Guadalupe Alcántara Rojas','party':'pri'},
        {'chamber':'Dip.','id':'9218612','name':'María Guadalupe Cecilia Romero Castillo','party':'pan'},
        {'chamber':'Dip.','id':'9218492','name':'María Guadalupe Murguía Gutiérrez','party':'pan'},
        {'chamber':'Dip.','id':'9219580','name':'María Guadalupe Oyervides Valdez','party':'pri'},
        {'chamber':'Dip.','id':'9219317','name':'María Isabel Maya Pineda','party':'pri'},
        {'chamber':'Dip.','id':'9219608','name':'María ívila Serna','party':'pvem'},
        {'chamber':'Dip.','id':'9219546','name':'María Luisa Beltrán Reyes','party':'prd'},
        {'chamber':'Dip.','id':'9218500','name':'María Luisa Sánchez Meza','party':'pan'},
        {'chamber':'Dip.','id':'9218399','name':'María Marcela González Salas y Petricioli','party':'pri'},
        {'chamber':'Dip.','id':'9218634','name':'María Mercedes Aguilar López','party':'pan'},
        {'chamber':'Dip.','id':'9218895','name':'María Monserrath Sobreyra Santos','party':'pri'},
        {'chamber':'Dip.','id':'9218468','name':'María Olimpia Zapata Padilla','party':'pan'},
        {'chamber':'Dip.','id':'9219089','name':'María Soledad Sandoval Martínez','party':'pri'},
        {'chamber':'Dip.','id':'9218598','name':'María Verónica Agundis Estrada','party':'pan'},
        {'chamber':'Dip.','id':'9219712','name':'María Verónica Muñoz Parra','party':'pri'},
        {'chamber':'Dip.','id':'9219778','name':'María Victoria Mercado Sánchez','party':'mc'},
        {'chamber':'Dip.','id':'9218436','name':'Mariana Arámbula Meléndez','party':'pan'},
        {'chamber':'Dip.','id':'9218359','name':'Mariana Benítez Tiburcio','party':'pri'},
        {'chamber':'Dip.','id':'9219492','name':'Mariana Trejo Flores','party':'morena'},
        {'chamber':'Dip.','id':'9219289','name':'Maricela Contreras Julián','party':'morena'},
        {'chamber':'Dip.','id':'9218326','name':'Maricela Emilse Etcheverry Aranda','party':'pri'},
        {'chamber':'Dip.','id':'9219464','name':'Maricela Serrano Hernández','party':'pri'},
        {'chamber':'Dip.','id':'9219520','name':'Mario Ariel Juárez Rodríguez','party':'morena'},
        {'chamber':'Dip.','id':'9219726','name':'Mario Machuca Sánchez','party':'pvem'},
        {'chamber':'Dip.','id':'9218804','name':'Marisol Vargas Bárcena','party':'pan'},
        {'chamber':'Dip.','id':'9218756','name':'Marko Antonio Cortés Mendoza','party':'pan'},
        {'chamber':'Dip.','id':'9218454','name':'Martha Cristina Jiménez Márquez','party':'pan'},
        {'chamber':'Dip.','id':'9219466','name':'Martha Hilda González Calderón','party':'pri'},
        {'chamber':'Dip.','id':'9218735','name':'Martha Lorena Covarrubias Anaya','party':'pri'},
        {'chamber':'Dip.','id':'9218297','name':'Martha Sofía Tamayo Morales','party':'pri'},
        {'chamber':'Dip.','id':'9218393','name':'Matías Nazario Morales','party':'pri'},
        {'chamber':'Dip.','id':'9218466','name':'Mayra Angélica Enríquez Vanderkam','party':'pan'},
        {'chamber':'Dip.','id':'9219497','name':'Melissa Torres Sandoval','party':'panal'},
        {'chamber':'Dip.','id':'9219664','name':'Mercedes del Carmen Guillén Vicente','party':'pri'},
        {'chamber':'Dip.','id':'9219506','name':'Miguel Alva y Alva','party':'morena'},
        {'chamber':'Dip.','id':'9219007','name':'Miguel íngel González Salum','party':'pri'},
        {'chamber':'Dip.','id':'9218666','name':'Miguel íngel Huepa Pérez','party':'pan'},
        {'chamber':'Dip.','id':'9218865','name':'Miguel íngel Ramírez Ponce','party':'pri'},
        {'chamber':'Dip.','id':'9218524','name':'Miguel íngel Salim Alle','party':'pan'},
        {'chamber':'Dip.','id':'9219495','name':'Miguel íngel Sedas Castro','party':'pvem'},
        {'chamber':'Dip.','id':'9218900','name':'Miguel íngel Sulub Caamal','party':'pri'},
        {'chamber':'Dip.','id':'9218676','name':'Minerva Hernández Ramos','party':'pan'},
        {'chamber':'Dip.','id':'9218335','name':'Miriam Dennis Ibarra Rangel','party':'pri'},
        {'chamber':'Dip.','id':'9219482','name':'Mirna Isabel Saldívar Paz','party':'panal'},
        {'chamber':'Dip.','id':'9219420','name':'Mirza Flores Gómez','party':'mc'},
        {'chamber':'Dip.','id':'9219556','name':'Modesta Fuentes Alonso','party':'morena'},
        {'chamber':'Dip.','id':'9219678','name':'Moisés Guerra Mota','party':'mc'},
        {'chamber':'Dip.','id':'9218630','name':'Mónica Rodríguez Della Vecchia','party':'pan'},
        {'chamber':'Dip.','id':'9218331','name':'Montserrat Alicia Arcos Velázquez','party':'pri'},
        {'chamber':'Dip.','id':'9218440','name':'Nadia Haydee Vega Olivas','party':'pan'},
        {'chamber':'Dip.','id':'9221523','name':'Nancy Guadalupe Sánchez Arredondo','party':'pri'},
        {'chamber':'Dip.','id':'9219225','name':'Nancy López Ruiz','party':'pes'},
        {'chamber':'Dip.','id':'9219269','name':'Natalia Karina Barón Ortiz','party':'morena'},
        {'chamber':'Dip.','id':'9218566','name':'Nelly del Carmen Márquez Zapata','party':'pan'},
        {'chamber':'Dip.','id':'9219532','name':'Noemí Zoila Guzmán Lagunes','party':'pri'},
        {'chamber':'Dip.','id':'9218712','name':'Nora Liliana Oropeza Olguín','party':'pri'},
        {'chamber':'Dip.','id':'9219704','name':'Norberto Antonio Martínez Soto','party':'prd'},
        {'chamber':'Dip.','id':'9219217','name':'Norma Edith Martínez Guzmán','party':'pes'},
        {'chamber':'Dip.','id':'9219658','name':'Norma Rocío Nahle García','party':'morena'},
        {'chamber':'Dip.','id':'9219486','name':'Norma Xóchitl Hernández Colín','party':'morena'},
        {'chamber':'Dip.','id':'9219572','name':'Olga Catalán Padilla','party':'prd'},
        {'chamber':'Dip.','id':'9218867','name':'Olga María Esquivel Hernández','party':'pri'},
        {'chamber':'Dip.','id':'9218606','name':'Omar Noé Bernardino Vargas','party':'pvem'},
        {'chamber':'Dip.','id':'9219353','name':'Omar Ortega Álvarez','party':'prd'},
        {'chamber':'Dip.','id':'9219594','name':'Óscar Ferrer Abalos','party':'prd'},
        {'chamber':'Dip.','id':'9219077','name':'Óscar García Barrón','party':'pri'},
        {'chamber':'Dip.','id':'9219016','name':'Óscar Valencia García','party':'pri'},
        {'chamber':'Dip.','id':'9218361','name':'Oswaldo Guillermo Cházaro Montalvo','party':'pri'},
        {'chamber':'Dip.','id':'9219099','name':'Otniel García Navarro','party':'pri'},
        {'chamber':'Dip.','id':'9218997','name':'Pablo Basáñez García','party':'pri'},
        {'chamber':'Dip.','id':'9219179','name':'Pablo Bedolla López','party':'pri'},
        {'chamber':'Dip.','id':'9219047','name':'Pablo Elizondo García','party':'pri'},
        {'chamber':'Dip.','id':'9219194','name':'Pablo Gamboa Miner','party':'pri'},
        {'chamber':'Dip.','id':'9218991','name':'Paloma Canales Suárez','party':'pvem'},
        {'chamber':'Dip.','id':'9219053','name':'Paola Iveth Gárate Valenzuela','party':'pri'},
        {'chamber':'Dip.','id':'9219688','name':'Patricia Elena Aceves Pastrana','party':'morena'},
        {'chamber':'Dip.','id':'9218518','name':'Patricia García García','party':'pan'},
        {'chamber':'Dip.','id':'9218570','name':'Patricia Sánchez Carrillo','party':'pan'},
        {'chamber':'Dip.','id':'9219059','name':'Pedro Alberto Salazar Muciño','party':'pri'},
        {'chamber':'Dip.','id':'9221527','name':'Pedro Garza Treviño','party':'pan'},
        {'chamber':'Dip.','id':'9218883','name':'Pedro Luis Coronado Ayarzagoitia','party':'pri'},
        {'chamber':'Dip.','id':'9218726','name':'Pedro Luis Noble Monterrubio','party':'pri'},
        {'chamber':'Dip.','id':'9219182','name':'Próspero Manuel Ibarra Otero','party':'pri'},
        {'chamber':'Dip.','id':'9218999','name':'Rafael Arturo Balcázar Narro','party':'pri'},
        {'chamber':'Dip.','id':'9219229','name':'Rafael Hernández Soriano','party':'prd'},
        {'chamber':'Dip.','id':'9218456','name':'Rafael Valenzuela Armas','party':'pan'},
        {'chamber':'Dip.','id':'9218275','name':'Rafael Yerena Zambrano','party':'pri'},
        {'chamber':'Dip.','id':'9219450','name':'Ramón Bañales Arambula','party':'pri'},
        {'chamber':'Dip.','id':'9219311','name':'Ramón VillaGómez Guerrero','party':'pri'},
        {'chamber':'Dip.','id':'9218923','name':'Raúl Domínguez Rex','party':'pri'},
        {'chamber':'Dip.','id':'9219133','name':'Refugio Trinidad Garzón Canchola','party':'pes'},
        {'chamber':'Dip.','id':'9218417','name':'Renato Josafat Molina Arias','party':'morena'},
        {'chamber':'Dip.','id':'9219668','name':'René Cervera García','party':'morena'},
        {'chamber':'Dip.','id':'9221529','name':'René Mandujano Tinajero','party':'pan'},
        {'chamber':'Dip.','id':'9219666','name':'Ricardo David García Portilla','party':'pri'},
        {'chamber':'Dip.','id':'9218453','name':'Ricardo Del Rivero Martínez','party':'pan'},
        {'chamber':'Dip.','id':'9219686','name':'Ricardo íngel Barrientos Ríos','party':'prd'},
        {'chamber':'Dip.','id':'9219127','name':'Ricardo Ramírez Nieto','party':'pri'},
        {'chamber':'Dip.','id':'9219738','name':'Ricardo Taja Ramírez','party':'pri'},
        {'chamber':'Dip.','id':'9219343','name':'Roberto Alejandro Cañedo Jiménez','party':'morena'},
        {'chamber':'Dip.','id':'9219512','name':'Roberto Guzmán Jacobo','party':'morena'},
        {'chamber':'Dip.','id':'9219041','name':'Rocío Díaz Montoya','party':'pri'},
        {'chamber':'Dip.','id':'9219684','name':'Rocío Matesanz Santamaría','party':'pan'},
        {'chamber':'Dip.','id':'9219500','name':'Rodrigo Abdala Dartigues','party':'morena'},
        {'chamber':'Dip.','id':'9219347','name':'Rogerio Castro Vázquez','party':'morena'},
        {'chamber':'Dip.','id':'9218604','name':'Román Francisco Cortés Lugo','party':'pan'},
        {'chamber':'Dip.','id':'9219430','name':'Rosa Alba Ramírez Nachis','party':'mc'},
        {'chamber':'Dip.','id':'9218433','name':'Rosa Alicia Álvarez Piñones','party':'pvem'},
        {'chamber':'Dip.','id':'9219003','name':'Rosa Guadalupe Chávez Acosta','party':'pri'},
        {'chamber':'Dip.','id':'9221522','name':'Rosalina Mazari Espín','party':'pri'},
        {'chamber':'Dip.','id':'9218963','name':'Rosalinda Muñoz Sánchez','party':'pri'},
        {'chamber':'Dip.','id':'9219336','name':'Rubén Alejandro Garrido Muñoz','party':'pan'},
        {'chamber':'Dip.','id':'9219319','name':'Ruth Noemí Tiscareño Agoitia','party':'pri'},
        {'chamber':'Dip.','id':'9221518','name':'Salomón Fernando Rosales Reyes','party':'pri'},
        {'chamber':'Dip.','id':'9219700','name':'Salomón Majul González','party':'pri'},
        {'chamber':'Dip.','id':'9219428','name':'Salvador Zamora Zamora','party':'mc'},
        {'chamber':'Dip.','id':'9218717','name':'Samuel Alexis Chacón Morales','party':'pri'},
        {'chamber':'Dip.','id':'9218901','name':'Samuel Rodríguez Torres','party':'pvem'},
        {'chamber':'Dip.','id':'9218420','name':'Sandra Luz Falcón Venegas','party':'morena'},
        {'chamber':'Dip.','id':'9219202','name':'Sandra Méndez Hernández','party':'pri'},
        {'chamber':'Dip.','id':'9218614','name':'Santiago Taboada Cortina','party':'pan'},
        {'chamber':'Dip.','id':'9218660','name':'Santiago Torreblanca Engell','party':'pan'},
        {'chamber':'Dip.','id':'9218911','name':'Santos Garza Herrera','party':'pri'},
        {'chamber':'Dip.','id':'9219456','name':'Sara Latife Ruiz Chávez','party':'pri'},
        {'chamber':'Dip.','id':'9219480','name':'Sara Paola Galico Félix Díaz','party':'morena'},
        {'chamber':'Dip.','id':'9219720','name':'Sasil Dora Luz De León Villard','party':'pvem'},
        {'chamber':'Dip.','id':'9221506','name':'Sergio Emilio Gómez Oliver','party':'pan'},
        {'chamber':'Dip.','id':'9218263','name':'Sergio López Sánchez','party':'prd'},
        {'chamber':'Dip.','id':'9218910','name':'Sharon María Teresa Cuenca Ayala','party':'pvem'},
        {'chamber':'Dip.','id':'9219698','name':'Silvia Rivera Carbajal','party':'pri'},
        {'chamber':'Dip.','id':'9218975','name':'Sofia del Sagrario De León Maza','party':'pri'},
        {'chamber':'Dip.','id':'9219455','name':'Sofía González Torres','party':'pvem'},
        {'chamber':'Dip.','id':'9219548','name':'Susana Corella Platt','party':'pri'},
        {'chamber':'Dip.','id':'9221516','name':'Susana Osorno Belmont','party':'pri'},
        {'chamber':'Dip.','id':'9218305','name':'Sylvana Beltrones Sánchez','party':'pri'},
        {'chamber':'Dip.','id':'9219257','name':'Tania Victoria Arguijo Herrera','party':'prd'},
        {'chamber':'Dip.','id':'9218939','name':'Telésforo García Carreón','party':'pri'},
        {'chamber':'Dip.','id':'9218432','name':'Teresa de Jesús Lizárraga Figueroa','party':'pan'},
        {'chamber':'Dip.','id':'9219618','name':'Timoteo Villa Ramírez','party':'pri'},
        {'chamber':'Dip.','id':'9219371','name':'Tomás Octaviano Félix','party':'prd'},
        {'chamber':'Dip.','id':'9218329','name':'Tomás Roberto Montoya Díaz','party':'pri'},
        {'chamber':'Dip.','id':'9218694','name':'Tristán Manuel Canales Najjar','party':'pri'},
        {'chamber':'Dip.','id':'9219722','name':'Uberly López Roblero','party':'pvem'},
        {'chamber':'Dip.','id':'9218674','name':'Ulises Ramírez Núñez','party':'pan'},
        {'chamber':'Dip.','id':'9219422','name':'Verónica Delgadillo García','party':'mc'},
        {'chamber':'Dip.','id':'9218584','name':'Víctor Ernesto Ibarra Montoya','party':'pan'},
        {'chamber':'Dip.','id':'9219650','name':'Víctor Manuel Giorgana Jiménez','party':'pri'},
        {'chamber':'Dip.','id':'9219640','name':'Víctor Manuel Sánchez Orozco','party':'mc'},
        {'chamber':'Dip.','id':'9218704','name':'Víctor Manuel Silva Tejeda','party':'pri'},
        {'chamber':'Dip.','id':'9219692','name':'Victoriano Wences Real','party':'prd'},
        {'chamber':'Dip.','id':'9219067','name':'Victorino Cruz Campos','party':'pri'},
        {'chamber':'Dip.','id':'9219448','name':'Vidal Llerenas Morales','party':'morena'},
        {'chamber':'Dip.','id':'9218353','name':'Virgilio Daniel Méndez Bazán','party':'pri'},
        {'chamber':'Dip.','id':'9219438','name':'Virgilio Dante Caballero Pedraza','party':'morena'},
        {'chamber':'Dip.','id':'9219734','name':'Virgilio Mendoza Amezcua','party':'pvem'},
        {'chamber':'Dip.','id':'9219514','name':'Virginia Nallely Gutiérrez Ramírez','party':'pri'},
        {'chamber':'Dip.','id':'9218955','name':'Vitalico Cándido Coheto Martínez','party':'pri'},
        {'chamber':'Dip.','id':'9219259','name':'Waldo Fernández González','party':'prd'},
        {'chamber':'Dip.','id':'9218494','name':'Wenceslao Martínez Santos','party':'pan'},
        {'chamber':'Dip.','id':'9219560','name':'Wendolin Toledo Aceves','party':'pvem'},
        {'chamber':'Dip.','id':'9218626','name':'Ximena Tamariz García','party':'pan'},
        {'chamber':'Dip.','id':'9218875','name':'Xitlalic Ceja García','party':'pri'},
        {'chamber':'Dip.','id':'9219361','name':'Yahleel Abdala Carmona','party':'pri'},
        {'chamber':'Dip.','id':'9221517','name':'Yaret Adriana Guevara Jiménez','party':'pvem'},
        {'chamber':'Dip.','id':'9218993','name':'Yarith Tannos Cruz','party':'pri'},
        {'chamber':'Dip.','id':'9219588','name':'Yerico Abramo Masso','party':'pri'},
        {'chamber':'Dip.','id':'9219592','name':'Yulma Rocha Aguilar','party':'pri'},
        {'chamber':'Dip.','id':'9218339','name':'Zacil Leonor Moguel Manzur','party':'pri'},
        {'chamber':'Sen.','id':'9219155','name':'Aarón Irízar López','party':'pri'},
        {'chamber':'Sen.','id':'9218048','name':'Adán Augusto López Hernández','party':'prd'},
        {'chamber':'Sen.','id':'9221489','name':'Adolfo Romero Lainas','party':'prd'},
        {'chamber':'Sen.','id':'9219213','name':'Adriana Dávila Fernández','party':'pan'},
        {'chamber':'Sen.','id':'9217488','name':'Agustín Trujillo Íñiguez','party':'pri'},
        {'chamber':'Sen.','id':'9221298','name':'Alejandro de Jesús Encinas Rodríguez','party':'ind.'},
        {'chamber':'Sen.','id':'9216284','name':'Alejandro Tello Cristerna','party':'pri'},
        {'chamber':'Sen.','id':'9217886','name':'Alonso José Ricardo Lujambio Irazábal','party':'pan'},
        {'chamber':'Sen.','id':'9221179','name':'Ana Gabriela Guevara Espinoza','party':'pt'},
        {'chamber':'Sen.','id':'9218840','name':'Ana Lilia Herrera Anzaldo','party':'pri'},
        {'chamber':'Sen.','id':'9220634','name':'Anabel Acosta Islas','party':'pri'},
        {'chamber':'Sen.','id':'9221356','name':'Andrea García García','party':'pan'},
        {'chamber':'Sen.','id':'9221350','name':'Ángel Benjamín Robles Montoya','party':'pt'},
        {'chamber':'Sen.','id':'9221167','name':'Angélica De la Peña Gómez','party':'prd'},
        {'chamber':'Sen.','id':'9219540','name':'Angélica del Rosario Araujo Lara','party':'pri'},
        {'chamber':'Sen.','id':'9217904','name':'Arely Gómez González','party':'pri'},
        {'chamber':'Sen.','id':'9220861','name':'Armando Neyra Chávez','party':'pri'},
        {'chamber':'Sen.','id':'9221294','name':'Armando Ríos Piter','party':'ind.'},
        {'chamber':'Sen.','id':'9219048','name':'Arturo Zamora Jiménez','party':'pri'},
        {'chamber':'Sen.','id':'9219110','name':'Blanca María del Socorro Alcalá Ruiz','party':'pri'},
        {'chamber':'Sen.','id':'9215546','name':'Braulio Manuel Fernández Aguirre','party':'pri'},
        {'chamber':'Sen.','id':'9221317','name':'Carlos Alberto Puente Salas','party':'pvem'},
        {'chamber':'Sen.','id':'9220869','name':'Carlos Antonio Romero Deschamps','party':'pri'},
        {'chamber':'Sen.','id':'9221309','name':'Carlos Manuel Merino Campos','party':'pt'},
        {'chamber':'Sen.','id':'9215526','name':'Carlos Mendoza Davis','party':'pan'},
        {'chamber':'Sen.','id':'9220747','name':'Carmen Dorantes Martínez','party':'pri'},
        {'chamber':'Sen.','id':'9221295','name':'Celestino Cesareo Guzmán','party':'prd'},
        {'chamber':'Sen.','id':'9219153','name':'César Octavio Pedroza Gaitán','party':'pan'},
        {'chamber':'Sen.','id':'9215901','name':'Claudia Artemiza Pavlovich Arellano','party':'pri'},
        {'chamber':'Sen.','id':'9219157','name':'Daniel Amador Gaxiola','party':'pri'},
        {'chamber':'Sen.','id':'9219528','name':'Daniel Gabriel Ávila Ruiz','party':'pan'},
        {'chamber':'Sen.','id':'9219149','name':'Daniel Torres Cantú','party':'ind.'},
        {'chamber':'Sen.','id':'9221321','name':'David Monreal Ávila','party':'pt'},
        {'chamber':'Sen.','id':'9215780','name':'David Penchyna Grub','party':'pri'},
        {'chamber':'Sen.','id':'9220863','name':'Diva Hadamira Gastélum Bajo','party':'pri'},
        {'chamber':'Sen.','id':'9219393','name':'Edgar Spinoso Carrera','party':'ind.'},
        {'chamber':'Sen.','id':'9221000','name':'Emilio Antonio Gamboa Patrón','party':'pri'},
        {'chamber':'Sen.','id':'9219121','name':'Enrique Burgos García','party':'pri'},
        {'chamber':'Sen.','id':'9219191','name':'Ernesto Gándara Camou','party':'pri'},
        {'chamber':'Sen.','id':'9221134','name':'Ernesto Javier Cordero Arroyo','party':'pan'},
        {'chamber':'Sen.','id':'9218784','name':'Ernesto Ruffo Appel','party':'pan'},
        {'chamber':'Sen.','id':'9220702','name':'Esteban Albarrán Mendoza','party':'pri'},
        {'chamber':'Sen.','id':'9215836','name':'Eviel Pérez Magaña','party':'pri'},
        {'chamber':'Sen.','id':'9219135','name':'Félix Arturo González Canto','party':'pri'},
        {'chamber':'Sen.','id':'9221310','name':'Fernando Enrique Mayans Canabal','party':'prd'},
        {'chamber':'Sen.','id':'9221495','name':'Fernando Herrera Ávila','party':'pan'},
        {'chamber':'Sen.','id':'9218846','name':'Fernando Torres Graciano','party':'pan'},
        {'chamber':'Sen.','id':'9216264','name':'Fernando Yunes Márquez','party':'pan'},
        {'chamber':'Sen.','id':'9221342','name':'Fidel Demédicis Hidalgo','party':'pt'},
        {'chamber':'Sen.','id':'9219193','name':'Francisco de Paula Búrquez Valenzuela','party':'pan'},
        {'chamber':'Sen.','id':'9215865','name':'Francisco Domínguez Servién','party':'pan'},
        {'chamber':'Sen.','id':'9215945','name':'Francisco Javier García Cabeza de Vaca','party':'pan'},
        {'chamber':'Sen.','id':'9219159','name':'Francisco Salvador López Brito','party':'pan'},
        {'chamber':'Sen.','id':'9221144','name':'Gabriela Cuevas Barrón','party':'pan'},
        {'chamber':'Sen.','id':'9220865','name':'Gerardo Sánchez García','party':'pri'},
        {'chamber':'Sen.','id':'9220867','name':'Graciela Ortiz González','party':'pri'},
        {'chamber':'Sen.','id':'9221044','name':'Héctor David Flores Ávalos','party':'pan'},
        {'chamber':'Sen.','id':'9221150','name':'Héctor Larios Córdova','party':'pan'},
        {'chamber':'Sen.','id':'9219538','name':'Héctor Yunes Landa','party':'pri'},
        {'chamber':'Sen.','id':'9220643','name':'Hilda Ceballos Llerenas','party':'pri'},
        {'chamber':'Sen.','id':'9221487','name':'Hilda Esthela Flores Escalera','party':'pri'},
        {'chamber':'Sen.','id':'9220665','name':'Humberto Domingo Mayans Canabal','party':'pri'},
        {'chamber':'Sen.','id':'9221175','name':'Iris Vianey Mendoza Mendoza','party':'prd'},
        {'chamber':'Sen.','id':'9221065','name':'Irma Patricia Leal Islas','party':'pan'},
        {'chamber':'Sen.','id':'9219740','name':'Isaías González Cuevas','party':'pri'},
        {'chamber':'Sen.','id':'9221340','name':'Isidro Pedraza Chávez','party':'prd'},
        {'chamber':'Sen.','id':'9218832','name':'Ismael Alfredo Hernández Deras','party':'pri'},
        {'chamber':'Sen.','id':'9221230','name':'Itzel Sarahí Ríos de la Mora','party':'pri'},
        {'chamber':'Sen.','id':'9219094','name':'Ivonne Liliana Álvarez García','party':'pri'},
        {'chamber':'Sen.','id':'9217780','name':'Javier Corral Jurado','party':'pan'},
        {'chamber':'Sen.','id':'9219116','name':'Javier Lozano Alarcón','party':'pan'},
        {'chamber':'Sen.','id':'9220502','name':'Jesús Casillas Romero','party':'pri'},
        {'chamber':'Sen.','id':'9220746','name':'Jesús priego Calva','party':'pri'},
        {'chamber':'Sen.','id':'9220873','name':'Joel Ayala Almeida','party':'pri'},
        {'chamber':'Sen.','id':'9220768','name':'Jorge Aréchiga Ávila','party':'pvem'},
        {'chamber':'Sen.','id':'9217507','name':'Jorge Emilio González Martínez','party':'pvem'},
        {'chamber':'Sen.','id':'9218800','name':'Jorge Luis Lavalle Maury','party':'pan'},
        {'chamber':'Sen.','id':'9218816','name':'Jorge Luis Preciado Rodríguez','party':'pan'},
        {'chamber':'Sen.','id':'9220757','name':'Jorge Toledo Luis','party':'pri'},
        {'chamber':'Sen.','id':'9219062','name':'José Ascención Orihuela Bárcenas','party':'pri'},
        {'chamber':'Sen.','id':'9221026','name':'José de Jesús Santana García','party':'pan'},
        {'chamber':'Sen.','id':'9219536','name':'José Francisco Yunes Zorrilla','party':'pri'},
        {'chamber':'Sen.','id':'9220771','name':'José Marco Antonio Olvera Acevedo','party':'pri'},
        {'chamber':'Sen.','id':'9219054','name':'José María Martínez Martínez','party':'pan'},
        {'chamber':'Sen.','id':'9220672','name':'José María Tapia Franco','party':'pri'},
        {'chamber':'Sen.','id':'9215576','name':'José Rosas Aispuro Torres','party':'pan'},
        {'chamber':'Sen.','id':'9221030','name':'Juan Alejandro Fernández Sánchez Navarro','party':'pan'},
        {'chamber':'Sen.','id':'9218848','name':'Juan Carlos Romero Hicks','party':'pan'},
        {'chamber':'Sen.','id':'9221189','name':'Juan Gerardo Flores Ramírez','party':'pvem'},
        {'chamber':'Sen.','id':'9215574','name':'Juana Leticia Herrera Ale','party':'pri'},
        {'chamber':'Sen.','id':'9221148','name':'Laura Angélica Rojas Hernández','party':'pan'},
        {'chamber':'Sen.','id':'9221199','name':'Layda Elena Sansores San Román','party':'pt'},
        {'chamber':'Sen.','id':'9218826','name':'Lilia Guadalupe Merodio Reza','party':'pri'},
        {'chamber':'Sen.','id':'9220750','name':'Lisbeth Hernández Lecona','party':'pri'},
        {'chamber':'Sen.','id':'9221312','name':'Lorena Cuéllar Cisneros','party':'pt'},
        {'chamber':'Sen.','id':'9218822','name':'Luis Armando Melgar Bravo','party':'pvem'},
        {'chamber':'Sen.','id':'9218808','name':'Luis Fernando Salazar Fernández','party':'pan'},
        {'chamber':'Sen.','id':'9221336','name':'Luis Humberto Fernández Fuentes','party':'pt'},
        {'chamber':'Sen.','id':'9221165','name':'Luis Miguel Gerónimo Barbosa Huerta','party':'pt'},
        {'chamber':'Sen.','id':'9221140','name':'Luisa María de Guadalupe Calderón Hinojosa','party':'ind.'},
        {'chamber':'Sen.','id':'9221304','name':'Luz María Beristain Navarrete','party':'pt'},
        {'chamber':'Sen.','id':'9221147','name':'Ma. del Pilar Ortega Martínez','party':'pan'},
        {'chamber':'Sen.','id':'9215947','name':'Maki Esther Ortiz Domínguez','party':'pan'},
        {'chamber':'Sen.','id':'9221177','name':'Manuel Bartlett Díaz','party':'pt'},
        {'chamber':'Sen.','id':'9221329','name':'Manuel Cárdenas Fonseca','party':'ind.'},
        {'chamber':'Sen.','id':'9219201','name':'Manuel Cavazos Lerma','party':'pri'},
        {'chamber':'Sen.','id':'9219084','name':'Manuel Humberto Cota Jiménez','party':'pri'},
        {'chamber':'Sen.','id':'9219092','name':'Marcela Guerra Castillo','party':'pri'},
        {'chamber':'Sen.','id':'9221337','name':'Marco Antonio Blásquez Salinas','party':'pt'},
        {'chamber':'Sen.','id':'9219086','name':'Margarita Flores Sánchez','party':'pri'},
        {'chamber':'Sen.','id':'9221290','name':'María Alejandra Barrales Magdaleno','party':'prd'},
        {'chamber':'Sen.','id':'9221002','name':'María Cristina Díaz Salazar','party':'pri'},
        {'chamber':'Sen.','id':'9221171','name':'María de los Dolores Padierna Luna','party':'pt'},
        {'chamber':'Sen.','id':'9220329','name':'María del Carmen Izaguirre Francos','party':'pri'},
        {'chamber':'Sen.','id':'9219064','name':'María del Rocío Pineda Gochi','party':'pri'},
        {'chamber':'Sen.','id':'9221080','name':'María del Rosario Guzmán Avilés','party':'pan'},
        {'chamber':'Sen.','id':'9221191','name':'María Elena Barrera Tapia','party':'pvem'},
        {'chamber':'Sen.','id':'9220872','name':'María Hilaria Domínguez Arvizu','party':'pri'},
        {'chamber':'Sen.','id':'9220681','name':'María Lorena MarÁn Moreno','party':'pri'},
        {'chamber':'Sen.','id':'9220342','name':'María Lucero Saldaña Pérez','party':'pri'},
        {'chamber':'Sen.','id':'9221068','name':'María Marcela Torres Peimbert','party':'pan'},
        {'chamber':'Sen.','id':'9220522','name':'María Verónica Martínez Espinoza','party':'pri'},
        {'chamber':'Sen.','id':'9221136','name':'Mariana Gómez del Campo Gurza','party':'pan'},
        {'chamber':'Sen.','id':'9221292','name':'Mario Martín Delgado Carrillo','party':'pt'},
        {'chamber':'Sen.','id':'9221339','name':'Martha Angélica Tagle Martínez','party':'ind.'},
        {'chamber':'Sen.','id':'9219088','name':'Martha Elena García  Gómez','party':'pan'},
        {'chamber':'Sen.','id':'9221361','name':'Martha Palafox Gutiérrez','party':'prd'},
        {'chamber':'Sen.','id':'9218234','name':'Martín Orozco Sandoval','party':'pan'},
        {'chamber':'Sen.','id':'9217382','name':'Mely Romero Celis','party':'pri'},
        {'chamber':'Sen.','id':'9220642','name':'Mely Romero Celís','party':'pri'},
        {'chamber':'Sen.','id':'9220754','name':'Michelle Arandine Barrón Vivanco','party':'pri'},
        {'chamber':'Sen.','id':'9218842','name':'Miguel Ángel Chico Herrera','party':'pri'},
        {'chamber':'Sen.','id':'9221493','name':'Miguel Romo Medina','party':'pri'},
        {'chamber':'Sen.','id':'9217947','name':'Mónica Tzasna Arriola Gordillo','party':'panal'},
        {'chamber':'Sen.','id':'9221187','name':'Ninfa Clara Salinas Sada','party':'pvem'},
        {'chamber':'Sen.','id':'9215778','name':'Omar Fayad Meneses','party':'pri'},
        {'chamber':'Sen.','id':'9218798','name':'Óscar Román Rosas González','party':'pri'},
        {'chamber':'Sen.','id':'9218830','name':'Pablo Escudero Morales','party':'pvem'},
        {'chamber':'Sen.','id':'9218824','name':'Patricio Martínez García','party':'pri'},
        {'chamber':'Sen.','id':'9221344','name':'Rabindranath Salazar Solorio','party':'pt'},
        {'chamber':'Sen.','id':'9218796','name':'Raúl Aarón Pozos Lanz','party':'pri'},
        {'chamber':'Sen.','id':'9217615','name':'Raúl Cervantes Andrade','party':'pri'},
        {'chamber':'Sen.','id':'9221060','name':'Raúl Gracia Guzmán','party':'pan'},
        {'chamber':'Sen.','id':'9221300','name':'Raúl Morón Orozco','party':'ind.'},
        {'chamber':'Sen.','id':'9220753','name':'Raymundo García Chávez','party':'pri'},
        {'chamber':'Sen.','id':'9215772','name':'René Juárez Cisneros','party':'pri'},
        {'chamber':'Sen.','id':'9218788','name':'Ricardo Barroso Agramont','party':'pri'},
        {'chamber':'Sen.','id':'9220876','name':'Ricardo Urzúa Rivera','party':'pri'},
        {'chamber':'Sen.','id':'9218820','name':'Roberto Armando Albores Gleason','party':'pri'},
        {'chamber':'Sen.','id':'9221138','name':'Roberto Gil Zuarth','party':'pan'},
        {'chamber':'Sen.','id':'9219530','name':'Rosa Adriana Díaz Lizama','party':'pan'},
        {'chamber':'Sen.','id':'9221142','name':'Salvador Vega Casillas','party':'pan'},
        {'chamber':'Sen.','id':'9221076','name':'Sandra Luz García Guajardo','party':'pan'},
        {'chamber':'Sen.','id':'9221036','name':'Silvia Guadalupe Garza Galván','party':'pan'},
        {'chamber':'Sen.','id':'9221296','name':'Socorro Sofío Ramírez Hernández','party':'pri'},
        {'chamber':'Sen.','id':'9219151','name':'Sonia Mendoza Díaz','party':'pan'},
        {'chamber':'Sen.','id':'9221067','name':'Sonia Rocha Acosta','party':'pan'},
        {'chamber':'Sen.','id':'9221041','name':'Sylvia Leticia Martínez Elizondo','party':'pan'},
        {'chamber':'Sen.','id':'9219145','name':'Teófilo Torres Corzo','party':'pri'},
        {'chamber':'Sen.','id':'9219755','name':'Tereso Medina Ramírez','party':'pri'},
        {'chamber':'Sen.','id':'9221169','name':'Venancio Luis Sánchez Jiménez','party':'prd'},
        {'chamber':'Sen.','id':'9217810','name':'Vianey Montes Colunga','party':'pan'},
        {'chamber':'Sen.','id':'9218792','name':'Víctor Hermosillo y Celada','party':'pan'},
        {'chamber':'Sen.','id':'9218075','name':'Víctor Manuel Camacho Solís','party':'prd'},
        {'chamber':'Sen.','id':'9220745','name':'Yolanda De la Torre Valdez','party':'pri'},
        {'chamber':'Sen.','id':'9221285','name':'Zoe Alejandro Robledo Aburto','party':'pt'}
      ];
      return repos.map( function (repo) {
        repo.value = repo.name.toLowerCase();
        return repo;
      });
    }

    /**
     * Create filter function for a query string
     */
    function createFilterFor(query) {
      var lowercaseQuery = angular.lowercase(query);

      return function filterFn(item) {
        return (item.value.indexOf(lowercaseQuery) === 0);
      };

    }
  }
